### ISSUE TITLE
Test for batch aggregate signature with different values of n and m

### ISSUE THREAD

**Issue by durgesh-pandey** [ZenGo-X/multi-party-bls#17]
Hello,
I have looked into the batch aggregate signature test available here at  [1] .

This test works as expected but when I change the value of n and m being different, it looks to be failing in core aggregate verify where pairing doesn't match.
Specifically I modified your 3 of 3 for 3 message code to use 3 of 3 for 5 message as below:

```rust
// test batch 3 out of 3 for 5 messages
#[test]
fn agg_sig_test_3_batch_5() {
    let (key_vec, pk_vec, apk_vec) = keygen_batch(3, 5);

    let msg_vec = vec![[1].as_ref(), [2].as_ref(), [3].as_ref(), [4].as_ref(), [5].as_ref()];

    let bls_sig = sign_batch(3, &key_vec, &pk_vec, &msg_vec);

    // test batch aggregation to verify as correct
    assert_eq!(Keys::aggregate_verify(&apk_vec, &msg_vec, &bls_sig), true);

    // test verification to fail a bad entry in apk_vec
    let (_, _, bad_a_v) = keygen_batch(3, 5);
    assert_ne!(Keys::aggregate_verify(&bad_a_v, &msg_vec, &bls_sig), true);

    // test verification to fail a bad entry in msg_vec
    let bad_m_v = vec![[6].as_ref(), [7].as_ref(), [8].as_ref(), [9].as_ref(), [10].as_ref()];
    assert_ne!(Keys::aggregate_verify(&apk_vec, &bad_m_v, &bls_sig), true);

    // test verification to fail a bad bls signature
    let (bad_k_v, bad_p_v, _) = keygen_batch(3, 5);
    let bad_b_s = sign_batch(3, &bad_k_v, &bad_p_v, &msg_vec);
    assert_ne!(Keys::aggregate_verify(&apk_vec, &msg_vec, &bad_b_s), true);
}
```
Is this not supported and this is not a sound test, I might be missing some concept here. Or can there be any issue in the above test while computing the pairing?

Regards,

[1]: https://github.com/ZenGo-X/multi-party-bls/blob/20414ccca277416e7f880c56bca81832d72c06a2/src/aggregated_bls/test.rs#L36

**Comment by omershlo** [comment]
Thanks for reporting @durgesh-pandey ! 
we will take a look. Can you write down the specific error you get please ?

**Comment by durgesh-pandey** [comment]
It fails with assertion failed: `(left == right)` for "// test batch aggregation to verify as correct" i.e. on first aggregate_verify call. From debug prints, in core_aggregate_verify, the values of product1.e and product2.e  are different.

**Comment by durgesh-pandey** [comment]
Hey, Looks like I found the issue. In test code, it looks to be wrong iteration number for sign batch. 
created a PR for this with fix and additional tests : https://github.com/ZenGo-X/multi-party-bls/pull/18

**Comment by omershlo** [comment]
nice catch! 
I will review the PR shortly :)

**Comment by elichai** [comment]
Merged, Thanks!
